services:

  client1:
    image: govcms.api/govcms
    ports:
      - "{port}:80"
    volumes:
      - ./sites/{client}/modules:/var/www/html/modules/custom
      - ./sites/{client}/themes:/var/www/html/themes/custom
      - ./sites/{client}/sites:/var/www/html/sites:delegated

networks:
  govcms-api-network:
    external: true
  default:
    external: false
