---
apiVersion: v1
kind: Pod
metadata:
  name: cli
  labels:
    app: cli
spec:
  containers:
    - name: cli
      image: govcms/govcms:9.x-latest
      env:
        - name: LAGOON_ROUTE
          value: api.govcms.local

---
apiVersion: v1
kind: Pod
metadata:
  name: php
  labels:
    app: php
spec:
  containers:
    - name: php
      image: govcms/php:9.x-latest
      ports:
        - containerPort: 9000
      env:
        - name: LAGOON_ROUTE
          value: api.govcms.local
        - name: NGINX_FASTCGI_PASS
          value: php

---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: web
spec:
  containers:
    - name: nginx
      image: govcms/nginx-drupal:9.x-latest
      ports:
        - containerPort: 8080
      env:
        - name: LAGOON_ROUTE
          value: api.govcms.local
        - name: NGINX_FASTCGI_PASS
          value: php

---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb
      image: govcms/mariadb-drupal:9.x-latest
      ports:
        - containerPort: 3306
