---
apiVersion: v1
kind: Namespace
metadata:
  name: govcms-api
  labels:
    name: govcms-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: govcms-api
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
        - containerPort: 8443
