---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: govcms-api-cli
  labels:
    app: cli
spec:
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
    spec:
      volumes:
        - name: govcms-api-pv
          persistentVolumeClaim:
            claimName: govcms-api-pvc
      containers:
      - name: cli
        image: govcms/govcms:9.x-latest
        env:
        - name: LAGOON_ROUTE
          value: api.govcms.local
        volumeMounts:
          - mountPath: "/app/web/sites/default/files"
            subPath: "govcms-api"
            name: govcms-api-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: govcms-api-mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: govcms-api-pv-mysql
          persistentVolumeClaim:
            claimName: govcms-api-pvc-mysql
      containers:
      - name: mariadb
        image: govcms/mariadb-drupal:9.x-latest
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: govcms-api-pv-mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: govcms-api-php
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      volumes:
        - name: govcms-api-pv
          persistentVolumeClaim:
            claimName: govcms-api-pvc
      containers:
      - name: php
        image: govcms/php:9.x-latest
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: "/app/web/sites/default/files"
            subPath: "govcms-api"
            name: govcms-api-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: govcms-api-nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: govcms-api-pv
          persistentVolumeClaim:
            claimName: govcms-api-pvc
      containers:
      - name: nginx
        image: govcms/nginx-drupal:9.x-latest
        volumeMounts:
          - mountPath: "/app/web/sites/default/files"
            subPath: "govcms-api"
            name: govcms-api-pv
