services:

  client1:
    image: govcms.api/govcms-client
    environment:
      - VIRTUAL_HOST=client1.govcms.local
      - VIRTUAL_PORT=80
    ports:
      - "51002:80"
    volumes:
      - ./sites/client1/modules:/var/www/html/modules/custom
      - ./sites/client1/themes:/var/www/html/themes/custom
      - ./sites/client1/sites:/var/www/html/sites:delegated

networks:
  govcms-api-network:
    external: true
  default:
    external: false
